version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: echo-it-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echo-it-db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
